// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEr88-wu8NQFDkFvFJR9pgtD0y2hCVc4E',
    appId: '1:334212847711:android:a273fff8ac4d3a5527a3ea',
    messagingSenderId: '334212847711',
    projectId: 'tinderclone-4b2e5',
    storageBucket: 'tinderclone-4b2e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNvfOUevUUpDYE_Zyl58ojW-YBa--RY0c',
    appId: '1:334212847711:ios:67617edef9645ecb27a3ea',
    messagingSenderId: '334212847711',
    projectId: 'tinderclone-4b2e5',
    storageBucket: 'tinderclone-4b2e5.appspot.com',
    androidClientId: '334212847711-u77rjknp3df0u307040qpioi362teugj.apps.googleusercontent.com',
    iosClientId: '334212847711-n8tqi5blbtik6grgi2bcsp4o8h5c29qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantascan',
  );
}
